/*
 * This file was autogenerated using the ebf compiler.
 * See https://github.com/eightdatabits/ebf for more information on ebf.
 */

#ifndef EBF_H
#define EBF_H

#include <stdint.h>
#include <stddef.h>


typedef uint8_t cell_t;

extern cell_t* DP;

#endif /* EBF_H */
