/*
 * This file was autogenerated using the ebf compiler.
 * See https://github.com/eightdatabits/ebf for more information on ebf.
 */

#include <stdint.h>
#include <stddef.h>
#include <stdio.h>

#include "ebf.h"

#include "hooks.h"

cell_t* DP;

int main(void) {
    init_hook();

    /* Start User Application ============================================ */
    *DP += 1;
    *DP += 1;
    *DP += 1;
    *DP += 1;
    *DP += 1;
    *DP += 1;
    *DP += 1;
    *DP += 1;
    while(*DP!=0) {
    DP += 1;
    *DP += 1;
    *DP += 1;
    *DP += 1;
    *DP += 1;
    while(*DP!=0) {
    DP += 1;
    *DP += 1;
    *DP += 1;
    DP += 1;
    *DP += 1;
    *DP += 1;
    *DP += 1;
    DP += 1;
    *DP += 1;
    *DP += 1;
    *DP += 1;
    DP += 1;
    *DP += 1;
    DP -= 1;
    DP -= 1;
    DP -= 1;
    DP -= 1;
    *DP -= 1;
    }
    DP += 1;
    *DP += 1;
    DP += 1;
    *DP += 1;
    DP += 1;
    *DP -= 1;
    DP += 1;
    DP += 1;
    *DP += 1;
    while(*DP!=0) {
    DP -= 1;
    }
    DP -= 1;
    *DP -= 1;
    }
    *DP ^= *(DP+1);
    DP += 1;
    DP += 1;
    putchar(*DP);
    DP += 1;
    *DP -= 1;
    *DP -= 1;
    *DP -= 1;
    putchar(*DP);
    *DP += 1;
    *DP += 1;
    *DP += 1;
    *DP += 1;
    *DP += 1;
    *DP += 1;
    *DP += 1;
    putchar(*DP);
    putchar(*DP);
    *DP += 1;
    *DP += 1;
    *DP += 1;
    putchar(*DP);
    DP += 1;
    DP += 1;
    putchar(*DP);
    DP -= 1;
    *DP -= 1;
    putchar(*DP);
    DP -= 1;
    putchar(*DP);
    *DP += 1;
    *DP += 1;
    *DP += 1;
    putchar(*DP);
    *DP -= 1;
    *DP -= 1;
    *DP -= 1;
    *DP -= 1;
    *DP -= 1;
    *DP -= 1;
    putchar(*DP);
    *DP -= 1;
    *DP -= 1;
    *DP -= 1;
    *DP -= 1;
    *DP -= 1;
    *DP -= 1;
    *DP -= 1;
    *DP -= 1;
    putchar(*DP);
    DP += 1;
    DP += 1;
    *DP += 1;
    putchar(*DP);
    DP += 1;
    *DP += 1;
    *DP += 1;
    putchar(*DP);
    *DP -= 1;
    *DP -= 1;
    *DP -= 1;
    *DP -= 1;
    *DP -= 1;
    *DP -= 1;
    *DP -= 1;
    *DP -= 1;
    *DP -= 1;
    *DP -= 1;
    /* End User Application ============================================== */

    return *DP;
}
